// <auto-generated />
using ClosetItemApp.Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClosetItemApp.Api.Migrations
{
    [DbContext(typeof(ClosetItemListDbContext))]
    partial class ClosetItemListDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("ClosetItemApp.Api.ClosetItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ClosetItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Red",
                            ItemType = "Bottom",
                            ShortName = "Silk pants"
                        },
                        new
                        {
                            Id = 2,
                            Color = "Blue",
                            ItemType = "Bottom",
                            ShortName = "Jeans"
                        },
                        new
                        {
                            Id = 3,
                            Color = "Green",
                            ItemType = "Top",
                            ShortName = "Silk blouse"
                        },
                        new
                        {
                            Id = 4,
                            Color = "Brown",
                            ItemType = "Outerwear",
                            ShortName = "Fur coat"
                        },
                        new
                        {
                            Id = 5,
                            Color = "Brown",
                            ItemType = "Outerwear",
                            ShortName = "Leather jacket"
                        },
                        new
                        {
                            Id = 6,
                            Color = "White",
                            ItemType = "Accessory",
                            ShortName = "Pearl Necklace"
                        },
                        new
                        {
                            Id = 7,
                            Color = "Pink",
                            ItemType = "Top",
                            ShortName = "Sweatshirt"
                        },
                        new
                        {
                            Id = 8,
                            Color = "Blue",
                            ItemType = "Bottom",
                            ShortName = "Straightleg jeans"
                        },
                        new
                        {
                            Id = 9,
                            Color = "Black",
                            ItemType = "Footwear",
                            ShortName = "High Heels"
                        },
                        new
                        {
                            Id = 10,
                            Color = "Red/White",
                            ItemType = "Dress",
                            ShortName = "Polka-dot dress"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
